CREATE TABLE client (
id SERIAL PRIMARY KEY,
nui VARCHAR(10) UNIQUE NOT NULL,
full_name VARCHAR(255) NOT NULL,
address VARCHAR(255) NOT NULL
);

CREATE TABLE invoice (
id SERIAL PRIMARY KEY,
code VARCHAR(10) UNIQUE NOT NULL,
created_at TIMESTAMP NOT NULL,
total DECIMAL(10,2) NOT NULL,
client_id INT NOT NULL,
FOREIGN KEY (client_id) REFERENCES client (id)
);

CREATE TABLE product (
id SERIAL PRIMARY KEY,
description VARCHAR(255) NOT NULL,
brand VARCHAR(255) NOT NULL,
price DECIMAL(10,2) NOT NULL,
stock INT NOT NULL
);

CREATE TABLE detail (
id SERIAL PRIMARY KEY,
description VARCHAR(255) NOT NULL,
quantity INT NOT NULL,
price DECIMAL(10,2) NOT NULL,
invoice_id INT NOT NULL,
product_id INT NOT NULL,
FOREIGN KEY (invoice_id) REFERENCES invoice (id),
FOREIGN KEY (product_id) REFERENCES product (id)
);

